

services:
  web:
    image: vitorpinto500/superbowl:latest
    platform: linux/amd64
    build: .
    command: >
      sh -c "dockerize -wait tcp://${MYSQL_DATABASE_HOST}:${MYSQL_DATABASE_PORT} -timeout 60s &&
      flask run --host=0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "8080:5001"
    env_file:
      - .env.development
 
    networks:
      - backend

  mail:
    image: vitorpinto500/superbowl:latest
    command: ["python", "mail_service.py"]
    env_file:
      - .env.development
    ports:
      - "2525:587"
    networks:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "28000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge


volumes:
  mongo_data: