
services:
  web:
    build: .
    command: >
      sh -c "dockerize -wait tcp://mysql-1afb9ef7-staniaprojets-ffa9.j.aivencloud.com:24978 -timeout 60s &&
        flask run --host=0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DB_SECRETKEY=${DB_SECRETKEY}
      - DB_PASSWORDEMAIL=${DB_PASSWORDEMAIL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=mailtrap@demomailtrap.com
      
    networks:
      - backend

  mail:
    build: .
    platform: linux/amd64 
    environment:
      - MAIL_SERVER=live.smtp.mailtrap.io
      - MAIL_PORT=587
      - MAIL_USERNAME=api
      - MAIL_PASSWORD=${MAIL_PASSWORD}
  
    ports:
      - "0.0.0.0:587:587"
    networks:
      - backend

networks:
  backend:
    driver: bridge

