# fly.toml app configuration file generated for superbowlstania on 2024-04-29T15:38:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'superbowlstania'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3306

  [[services.ports]]
    port = 3306

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 5001

  [[services.ports]]
    port = 5000

  [[services.ports]]
    port = 5001

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 587

  [[services.ports]]
    port = 587

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  
[mounts]
  source = "mysqldata"
  destination = "/data"