# Configuración básica de la aplicación en Fly.io
app = app

# Definición del servicio Docker
[[services]]
  internal_port = 5000 # Puerto interno en el que Flask escucha las conexiones
  protocol = "tcp" # Protocolo que tu aplicación utiliza (en este caso, TCP para Flask)

  # Configuración del contenedor Docker
  [services.concurrency]
    hard_limit = 25 # Límite máximo de instancias de tu aplicación Docker
    soft_limit = 20 # Límite suave de instancias de tu aplicación Docker

  # Configuración específica para contenedores Docker
  [services.docker]
    # Define la imagen Docker que utilizará tu servicio
    image = app

# Más configuraciones pueden seguir aquí